package Vista;

import Modelo.LoginDAO;
import Modelo.login;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    //Instancia de mi clase login
    login lg = new login();
    //Instancia de mi clase LonginDao
    LoginDAO login = new LoginDAO();

    //Constructor de la clase
    public Login() {
        initComponents();
        //Para centrar la ventana de login en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }
    
    //Metodo para validar el acceso del usuario
    public void Validar() {
        //Se definen las variables que obtienen los datos del formulario
        String correo = txtCorreo.getText();
        String password = String.valueOf(txtPass.getPassword());              
                
        //Se verifica que no esten vacias las celdas del formulario
        if (!"".equals(correo) || !"".equals(password)) {
            //Se llama al metodo log con el correo y el password          
            lg = login.log(correo, password);
            //Se verifican que no sean nulos el correo y el password
            if (lg.getCorreo() != null && lg.getPass() != null) {
                
                //Se instancia un nuevo Form de tipo Sistema
                Sistema sis = new Sistema();
                //Se hace visible la instancia del Form sistema           
                sis.setVisible(true);                
                //Se cierra la ventana login
                dispose();
            } else {
                //Se muestra en pantalla el mensaje
                JOptionPane.showMessageDialog(null, "correo o la contraseña incorrecta");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnBackgroundLogin = new javax.swing.JPanel();
        lblTituloLogin = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginIcon = new javax.swing.JLabel();
        lblCorreoLogin = new javax.swing.JLabel();
        lblPasswordLogin = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        lblAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plnBackgroundLogin.setBackground(new java.awt.Color(51, 51, 51));

        lblTituloLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLogin.setText("Bienvenido al sistema de \"Control de la Producción\"");

        pnlLogin.setBackground(new java.awt.Color(153, 153, 153));
        pnlLogin.setForeground(new java.awt.Color(102, 102, 102));

        pnlLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user.png"))); // NOI18N

        lblCorreoLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorreoLogin.setForeground(new java.awt.Color(51, 51, 51));
        lblCorreoLogin.setText("Correo Electrónico");

        lblPasswordLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPasswordLogin.setForeground(new java.awt.Color(51, 51, 51));
        lblPasswordLogin.setText("Contraseña");

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresar.setBackground(new java.awt.Color(0, 102, 51));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnRegistrarse.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPasswordLogin)
                            .addComponent(lblCorreoLogin)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(pnlLoginIcon))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlLoginIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorreoLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasswordLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblAutor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor.setText("Codo a Codo 2022. Comisión 22587. Autor: Angel Garban");

        javax.swing.GroupLayout plnBackgroundLoginLayout = new javax.swing.GroupLayout(plnBackgroundLogin);
        plnBackgroundLogin.setLayout(plnBackgroundLoginLayout);
        plnBackgroundLoginLayout.setHorizontalGroup(
            plnBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addGroup(plnBackgroundLoginLayout.createSequentialGroup()
                .addGroup(plnBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plnBackgroundLoginLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plnBackgroundLoginLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblAutor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plnBackgroundLoginLayout.setVerticalGroup(
            plnBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnBackgroundLoginLayout.createSequentialGroup()
                .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblAutor)
                .addGap(16, 16, 16))
        );

        getContentPane().add(plnBackgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón Ingresar
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //Se llama al metodo validar datos de usuario  
        Validar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    //Botón Registrar nuevo usuario
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        //Se instancia un nuevo Form de tipo Registro
        Registro registro = new Registro();
        //Se hace visible la instancia del Form registro
        registro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCorreoLogin;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JPanel plnBackgroundLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JLabel pnlLoginIcon;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
